lookForAlignDelims:
  tikzcd: 1
  pmatrix: 1
modifyLineBreaks:
  textWrapOptions:
    columns: 80
    perCodeBlockBasis: 1
    all: 1
  removeParagraphLineBreaks:
    all: 1
    beforeTextWrap: 1
